### ISSUE TITLE
data read from BNO055 sensor using i2c

### ISSUE THREAD

**Issue by khalifima** [nebrius/raspi-io#103]
Hi 
I am using raspberry pi zero w to which i am connecting a bno055 sensor, when i follow the example provided in johnny-five to read data from the sensor I experience an odd behaviour, somehow in a random way some values have their most significant bit flipped from zero to 1. i am using node 8.x in raspbian stretch lite 03-2018

**Comment by khalifima** [comment]
:)

**Comment by nebrius** [comment]
I'm going to close this issue in favor of fivdi/i2c-bus#46, thanks for filing!
