### ISSUE TITLE
Create SPI straw-proposal

### ISSUE THREAD

**Issue by nebrius** [nebrius/raspi-io#106]
As part of getting SPI support into Johnny-five, create a straw-proposal for SPI in [raspi-io-core](https://github.com/nebrius/raspi-io-core) based on your initial work in [raspi-spi](https://github.com/nebrius/raspi-spi).

**Comment by nebrius** [comment]
Thinking on this one some more, I think this task is blocked by https://github.com/nebrius/raspi-io/issues/107, in practice

**Comment by geo242** [comment]
Now that #107 is closed, can this be revisited? I have tried using [pi-spi](https://github.com/natevw/pi-spi) while using raspi-io and it seems there is a conflict. SPI stops working as soon as raspi-io is initialized.

**Comment by nebrius** [comment]
I’m swamped with other projects unfortunately, so I don’t have time to work on this right now. That said, you can use the `excludePins` constructor option to exclude the SPI pins, allowing you to use pi-spi

**Comment by geo242** [comment]
@nebrius I did try that, but I used the include pins instead and just included the one pin I needed and that didn't help. I'll try the exclude and see if that operates differently.

**Comment by nebrius** [comment]
@geo242 thanks for being patient, I've been traveling. That's unusual, that should have worked. Can you show me the code you're running? I wonder if there's a bug in `includePins`

**Comment by nebrius** [comment]
Not going to work on this since this project is in maintenance mode
