### ISSUE TITLE
Raspi is not a constructor

### ISSUE THREAD

**Issue by Akil313** [nebrius/raspi-io#118]
Using a Raspberry Pi 3 Model B+
Installed Johnny-Five and Raspi-io

After installing, I ran this using node

```
const Raspi = require("raspi-io");
const five = require("johnny-five");

const board = five.Board(
    {
        io: new Raspi()
    }
);

board.on("ready", () => {
    let led = new five.Led('GPIO18');

    this.repl.inject({
        redLed: led
    });
})
```

After running with node, I get the error Raspi is not a constructor.
I've used the default code from the Johnny Five site and still no luck.

**Comment by Akil313** [comment]
After identifying the difference between the Raspberry Pi implementation from the Johnny Five website and this repo, I was able to get the code to run properly.
Specifically the change was `const Raspi = require("raspi-io");` to `const Raspi = require("raspi-io").RaspiIO;`

**Comment by dtex** [comment]
@Akil313 Was [this](https://github.com/rwaldron/johnny-five/blob/d2edcbe0557bdf4b91801f9b7f2121348eb4e4d2/docs/raspi-io.md) the page?

**Comment by Akil313** [comment]
Yea that's the one. Tried coping that exact code and ran into the error.

**Comment by nebrius** [comment]
Ah right, I forgot to update the code samples there when I did the big refactor. Thanks for looking into it @dtex. I'm still recovering from JSConf EU 😅
