### ISSUE TITLE
Unknown board revision b03111

### ISSUE THREAD

**Issue by irakandjii** [nebrius/raspi-io#120]

**Comment by irakandjii** [comment]
This is the code for a Raspberry Pi model 4 with 2 gigabytes of memory.  I trust this is useful.

**Comment by nebrius** [comment]
Thanks for the report @irakandjii! I just added support to raspi-board, the dependency raspi-io uses to identify board revisions.

**Comment by nebrius** [comment]
This issue should be fixed now, so I'm going to close this issue. Thanks again for the report!

**Comment by irakandjii** [comment]
Ok thank you for the notification
