### ISSUE TITLE
Raspberry Pi Zero support?

### ISSUE THREAD

**Issue by Japh** [nebrius/raspi-io#43]
Apologies if this is answered elsewhere, I didn't find mention specifically in the readme or other issues.

Does this support the RPi Zero? Could it?

Thanks! 😄

**Comment by nebrius** [comment]
It does, yes! I just now realized I didn't update the docs, so I'll do that next. Thanks for the issue, I wouldn't have realized this otherwise :)

**Comment by Japh** [comment]
Fantastic! Thanks, @nebrius

**Comment by Japh** [comment]
Oops, I'll leave it open til you update

**Comment by nebrius** [comment]
Docs are updated now!
