### ISSUE TITLE
Raspi-io support raspberry pi 3 module b or not ?

### ISSUE THREAD

**Issue by sensugaz** [nebrius/raspi-io#66]
nodejs johnny-five support on pi 3 model b or not 

thank your !

**Comment by nebrius** [comment]
Yes it's supported

**Comment by The-Alchemist** [comment]
I can confirm, as I used a GrovePi and a Raspberry Pi 3 Model B together for issue #65.

**Comment by norgeous** [comment]
please update the readme
https://github.com/nebrius/raspi-io/blob/master/README.md
and (if possible) also get pi 3 listed here:
http://johnny-five.io/platform-support/

**Comment by nebrius** [comment]
readme updated and PR submitted for the website: https://github.com/johnny-five-io/johnny-five.io/pull/101
