### ISSUE TITLE
need to be able to pass in serial config options

### ISSUE THREAD

**Issue by monteslu** [nebrius/raspi-io#78]
Since node serialport is being used for the serial* methods, we need to be able to pass config options from the raspi-io constructor on down to the serial port constructor.

The defaults in serial port now lock the port in linux which has the effect of only allowing us to initialize raspi-io once.  This breaks my node-red implementation in that I can't make changes and redeploy a flow.

**Comment by nebrius** [comment]
Which config options do you want to pass down?

**Comment by monteslu** [comment]
doh, I missed your reply @nebrius 

The main issue is that serialport now defaults to locking the port which means if we try re-initializing raspi-io in the same node instance we're blocked.

**Comment by nebrius** [comment]
I have two ideas for working around this. One is to set `lock` to `false`, the other is to listen to the `beforeExit` event and close the port there, but leaving it locked. The former is simpler, and I would guess would be more reliable, but I also worry about unintended side effects, especially if someone re-enables TTY console over serial.

**Comment by nebrius** [comment]
I just published 3.0.4 of raspi-serial, which includes the `beforeExit` approach to closing the port. Let me know if this works for you!

**Comment by monteslu** [comment]
It works!

Thanks, @nebrius

**Comment by nebrius** [comment]
Woo!
