### ISSUE TITLE
Error: Pin "7" does not support mode "4"

### ISSUE THREAD

**Issue by alopes** [nebrius/raspi-io#86]
Hey, I'm trying to connect a servo but when I run it I get that message. What does "mode 4" mean?
Thanks!

**Comment by alopes** [comment]
```
var board = new five.Board({
  io: new raspi({ enableSoftPwm: true })
});
```

Looks like **enableSoftPwm** needs to be passed in.

**Comment by nebrius** [comment]
Glad you figured it out! I just published an updated that makes this error a bit more descriptive.
