### ISSUE TITLE
Unable to get any movement from servo motors.

### ISSUE THREAD

**Issue by josephschenck** [nebrius/raspi-io#95]
I am trying to get a hang of raspi-io so I can use it in an upcoming project, but I am having difficulty getting any sort of movement from my servo motor. 

Whenever I attempt to run the code I have I get the following readout from console but the motor remains static.

> 1498166995719 Available RaspberryPi-IO  
> 1498166996078 Connected RaspberryPi-IO  
> 1498166996092 Repl Initialized  

Here is the code I am running

> var five = require("johnny-five");
> var Raspi = require("raspi-io");
> 
> var board = new five.Board({
>   io: new Raspi()
> });
> 
> board.on("ready", function() {
> 
>   var servo = new five.Servo({
>     pin: "P1-32",
>   });
>   servo.sweep();
> 
> });

**Comment by dtex** [comment]
@josephschenck How are you powering the servo? Is there a common ground?

**Comment by josephschenck** [comment]
I'm using a breadboard with an external power supply.
[http://i.imgur.com/xMkPe6l.jpg](url)

**Comment by nebrius** [comment]
Looking at that photo, it looks like you don't have a common ground. Try connecting a wire from a GND pin on the RPi to the ground rail on your breadboard and that should fix it.

**Comment by dtex** [comment]
@josephschenck Just noticed this issue was still open. Did adding a common ground help? Can we close this?

**Comment by josephschenck** [comment]
yea, closing it is fine

**Comment by nebrius** [comment]
Thanks for following up @dtex and @josephschenck!
