### ISSUE TITLE
Install script throws an error

### ISSUE THREAD

**Issue by rbwilcoxon11** [nebrius/raspi-io#97]
The install script seems to have a bug in it... I think it could be resolved if the right dependencies were installed.

Here's my package.json

```javascript
{
  ...
  "dependencies": {
   ...
    "raspi-io": "^8.1.0"
  },
  ...
```

When I run

```bash
npm install
```

I get this error back

```
> raspi-soft-pwm@4.0.1 preinstall /home/pi/hue-ball/node_modules/raspi-soft-pwm
> sh ./script/pigpio.sh

pigpio is already installed, skipping installation
npm ERR! Cannot read property 'pause' of undefined
```

I had installed this package about a week ago with no problems, I think it was the recent update. I could try to pull all the old packages, but I think it'd be easier just to fix this one...

**Comment by nebrius** [comment]
Hi @rbwilcoxon11! I ran into this issue too and documented it over at https://github.com/nebrius/raspi-io/issues/96.

Can you let me know which version of Node.js and npm you're running?

**Comment by rbwilcoxon11** [comment]
Node version - v8.5.0
npm version - 5.4.1

Right now i'm getting around it by installing all the dependencies manually and combining them like this files packages src

![image](https://user-images.githubusercontent.com/6274893/30491816-c0857db8-99fb-11e7-93b9-fd8888aae9c0.png)

The up-carrots are misleading though; each of those is the specific version I installed of each package

**Comment by nebrius** [comment]
Can you try downgrading to npm 5.3.0? That's what fixed it for me.

**Comment by rbwilcoxon11** [comment]
Works 👍
